##########################################################################
## Codes for the paper:
## Global determinants of freshwater and marine fish genetic diversity
## Authors :
## Stephanie Manel, Pierre-Edouard Guerin, David Mouillot,
## Simon Blanchet, Laure Velez, Camille Albouy, Loic Pellissier
## 
## Montpellier, 2017-2019
## Submited to Nature communications, 2019
##
##########################################################################
## This code is based on :
## An Anthropocene Map of Genetic Diversity
##
## Andreia Miraldo, Sen Li, Michael K. Borregaard,
## Alexander Floréz-Rodriguéz, Shyam Gopalakrishnan, Mirneza Risvanovic,
## Zhiheng Wang, Carsten Rahbek, Katharine A. Marske & David Nogués-Bravo
##
## Submitted to Science, 2016
## Code in this file by Michael K. Borregaard
## modified by P.E. GUERIN
## Montpellier 2017
#########################################################################
##
## functions to bootstrap by species latitudinal band genetic diversity
##
##
#########################################################################
using DataFrames

"""
bootstraping species latband

**Parameters**
* 'dat' :A master matrix data frame generated by the 'calc_cellvalues()' function
"""
function boot_species(dat::DataFrame)
    by(dat, :site) do df
        nrows = size(df, 1)
        rows = rand(1:nrows, nrows)
        mean(df[:GDspecies][rows])
    end
end


"""
Calculate values for bootstraping latband

**Parameters**
* 'dat' :A master matrix data frame generated by the 'calc_cellvalues()' function
* Number of bootstrap replicates 
"""
function bootstrap_species(dat::DataFrame, bR::Int64)
    boot_full = hcat([boot_species(dat)[:x1] for i in 1:bR]...) #creates a matrix of cell values
    ret = by(df -> mean(df[:GDspecies]), dat, :site)
    names!(ret, [:cell, :GD])
    ret[:GD_boot_sd] = vec(mapslices(std, boot_full, dims=2))
    ret
end

